package com.example.gamedesign.gameviews;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.view.MotionEvent;

import com.example.gamedesign.accountmanager.User;
import com.example.gamedesign.activities.RankingActivity;
import com.example.gamedesign.donttouchwhitetiles.DontTouchWhiteTilesController;
import com.example.gamedesign.gamestartactivity.TilesActivityStart;
import com.example.gamedesign.systemmanager.FileSaverLoader;

/** a class for Don't Touch White Tiles View */
public class DontTouchWhiteTilesView extends GameSurfaceView {

  /**
   * constructing a gameView for don't touch white tiles
   *
   * @param context context of the game activity
   * @param loggedUser user currently logged in
   * @param controller the game controller
   */
  public DontTouchWhiteTilesView(
      Context context,
      User loggedUser,
      DontTouchWhiteTilesController controller,
      FileSaverLoader fileSaverLoader) {
    super(context, fileSaverLoader, loggedUser, controller);
    this.pause();
    gamePresenter.initColor();
  }

  /**
   * get called when user tap on the screen
   *
   * @param event motion event generated by ontouchlistener
   */
  @Override
  public void onTouch(MotionEvent event) {
    if (gameStatus == GameStatus.PAUSED) {
      resume();
    } else if (gameStatus == GameStatus.PLAYING) {
      gamePresenter.onTouch(event);
    }
  }

  /** navigate to start game activity for don't touch white tiles game */
  @Override
  public void goToStartGameActivity() {
    Intent i = new Intent().setClass(getContext(), TilesActivityStart.class);
    gamePresenter.resetGame();
    getContext().startActivity(i);
  }

  /** @return the name of scoreboard owned by this game */
  @Override
  public String getScoreBoardName() {
    return RankingActivity.TILE_SCORE_BOARD;
  }

  /** animation to be displayed on screen */
  @Override
  protected void drawGame() {
    gamePresenter.draw(canvas);
    drawScoreGold(canvas);
  }

  /** time sleep after display */
  @Override
  protected void sleep() {
    try {
      Thread.sleep(30);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
